version: "3.8"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./:/app
    ports:
      - 8080:${AIR_PORT}
    environment:
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
    logging:
      options:
        max-size: "10m"
        max-file: "3"